# Generated by Django 5.1 on 2024-09-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurang',
            new_name='Restaurant',
        ),
    ]
